# Generated by Django 4.2 on 2023-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='general_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
