# Generated by Django 4.2 on 2023-05-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='general_type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
